const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => document.querySelectorAll(selector);
const api = async (url, options = {}) => { const token = localStorage.getItem('mealmeshToken'); const response = await fetch(`/api${url}`, { headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(options.headers || {}) }, ...options }); const contentType = response.headers.get('content-type') || ''; const data = contentType.includes('application/json') ? await response.json() : null; if (response.status === 401 && !url.startsWith('/auth/')) { localStorage.removeItem('mealmeshToken'); showAuth(data?.message || 'Your session has expired. Please log in again.'); } if (!response.ok) throw new Error(data?.message || `The server could not complete ${url}.`); if (!data) throw new Error(`The server returned an unexpected response for ${url}. Restart the backend and try again.`); return data; };
const dateValue = (date = new Date()) => new Date(date).toISOString().slice(0, 10);
const prettyDate = (date) => new Date(date).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
const escapeHtml = (text) => String(text).replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
let state = { meals: [], inventory: [], waste: [], procurement: [], dashboard: null, analytics: null };

function setAuthMessage(message = '') { const element = $('#auth-message'); element.textContent = message; element.classList.toggle('show', Boolean(message)); }
function showAuth(message = '') { $('.app-shell').style.display = 'none'; $('#auth-screen').classList.remove('hidden'); setAuthMessage(message); }
function showApp() { $('#auth-screen').classList.add('hidden'); $('.app-shell').style.removeProperty('display'); }
function saveSession(data) { localStorage.setItem('mealmeshToken', data.token); localStorage.setItem('mealmeshUser', JSON.stringify(data.user)); showApp(); refresh(); }
async function initializeSession() { if (!localStorage.getItem('mealmeshToken')) return showAuth(); try { await api('/auth/me'); showApp(); refresh(); } catch (error) { showAuth(error.message); } }
async function logout() { try { await api('/auth/logout', { method: 'POST' }); } catch (error) { /* Token removal still completes logout for this stateless JWT approach. */ } localStorage.removeItem('mealmeshToken'); localStorage.removeItem('mealmeshUser'); showAuth('You have been logged out.'); }

function toast(message, error = false) { const element = $('#toast'); element.textContent = message; element.className = `toast show${error ? ' error' : ''}`; clearTimeout(window.toastTimer); window.toastTimer = setTimeout(() => element.className = 'toast', 3200); }
function empty(text, cols = 1) { return `<tr><td colspan="${cols}" class="empty">${text}</td></tr>`; }
function setDashboardMessage(message, metric = '…') { ['#stat-students', '#stat-meals', '#stat-inventory', '#stat-low', '#stat-procurement', '#stat-waste'].forEach(selector => $(selector).textContent = metric); $('#today-meals').innerHTML = `<p class="empty">${message}</p>`; $('#low-stock').innerHTML = `<p class="empty">${message}</p>`; $('#recent-waste').innerHTML = `<p class="empty">${message}</p>`; }
function addIngredient(item = {}) { const node = $('#ingredient-template').content.cloneNode(true); const row = node.querySelector('.ingredient-row'); row.querySelector('.ingredient-name').value = item.name || ''; row.querySelector('.ingredient-quantity').value = item.quantityPerStudent || ''; row.querySelector('.ingredient-unit').value = item.unit || 'g'; row.querySelector('.remove-ingredient').onclick = () => row.remove(); $('#ingredient-list').append(node); }
function showPage(id) { document.querySelectorAll('.page').forEach(p => p.classList.toggle('active', p.id === id)); document.querySelectorAll('.nav-link').forEach(b => b.classList.toggle('active', b.dataset.page === id)); const titles = { dashboard: 'Good food starts with a clear plan.', meals: 'Plan meals with confidence.', inventory: 'Keep the pantry in balance.', procurement: 'Buy only what the kitchen needs.', waste: 'Make every portion count.' }; $('#page-title').textContent = titles[id]; if (id === 'procurement') loadProcurement(); }
async function refresh() { setDashboardMessage('Loading dashboard data…'); try { [state.meals, state.inventory, state.waste, state.procurement, state.dashboard] = await Promise.all([api('/meals'), api('/inventory'), api('/waste'), api('/procurement'), api('/dashboard')]); renderMeals(); renderInventory(); renderWaste(); renderProcurement(); renderDashboard(); loadPrediction(); loadAnalytics(); } catch (error) { state.dashboard = null; setDashboardMessage('Dashboard data could not be loaded.', '—'); $('#demand-prediction').innerHTML = '<p class="empty">Prediction is temporarily unavailable.</p>'; toast(error.message, true); } }
async function loadProcurement() { try { state.procurement = await api('/procurement'); renderProcurement(); renderDashboard(); } catch (error) { toast(error.message, true); } }
async function loadPrediction() { const container = $('#demand-prediction'); container.innerHTML = '<p class="empty">Loading prediction…</p>'; try { const prediction = await api('/predictions/demand'); if (!prediction.available) { $('#prediction-date').textContent = 'Upcoming lunch'; container.innerHTML = `<p class="empty">${escapeHtml(prediction.message)}</p>`; return; } $('#prediction-date').textContent = `${prediction.mealType} · ${prettyDate(prediction.date)}`; container.innerHTML = `<p class="prediction-value">${prediction.predictedStudents} students</p><p class="prediction-detail">${escapeHtml(prediction.explanation)}</p><p class="prediction-meta">${prediction.model}${prediction.mae !== null ? ` · MAE ${prediction.mae}` : ''} · ${prediction.historicalRecords} records</p>`; } catch (error) { container.innerHTML = '<p class="empty">Prediction is temporarily unavailable.</p>'; } }
function renderTrend(selector, trend, waste = false) { const container = $(selector); const maximum = Math.max(...trend.map(day => day.value), 1); container.innerHTML = trend.map(day => `<div class="trend-bar${waste ? ' waste' : ''}" style="height:${Math.max(3, (day.value / maximum) * 100)}%"><b>${day.value}</b><span>${day.label}</span></div>`).join(''); }
function renderAnalytics() { const { trends, procurement, prediction, recommendations } = state.analytics; renderTrend('#demand-trend', trends.demand); renderTrend('#waste-trend', trends.waste, true); $('#recommendations').innerHTML = recommendations.map(item => `<p class="recommendation">${escapeHtml(item.message)}</p>`).join(''); const capacity = prediction.available ? `<div class="capacity-line"><span>Predicted demand</span><b>${prediction.predictedStudents} servings</b></div><div class="capacity-line"><span>Planned capacity</span><b>${prediction.plannedCapacity} servings</b></div><div class="capacity-line"><span>Difference</span><b>${prediction.capacityDifference > 0 ? '+' : ''}${prediction.capacityDifference} servings</b></div>` : `<p class="empty">${escapeHtml(prediction.message)}</p>`; const purchases = procurement.length ? `<div class="capacity-line"><span>Items to purchase</span><b>${procurement.length}</b></div>${procurement.slice(0, 2).map(item => `<div class="capacity-line"><span>${escapeHtml(item.ingredient)}</span><b>${item.purchaseRequired} ${item.unit}</b></div>`).join('')}` : '<div class="capacity-line"><span>Procurement</span><b>Stock sufficient</b></div>'; $('#capacity-overview').innerHTML = capacity + purchases; }
async function loadAnalytics() { try { state.analytics = await api('/analytics'); renderAnalytics(); } catch (error) { ['#demand-trend', '#waste-trend', '#recommendations', '#capacity-overview'].forEach(selector => $(selector).innerHTML = '<p class="empty">Analytics are temporarily unavailable.</p>'); } }
function renderMeals() { $('#meal-count').textContent = `${state.meals.length} total`; $('#meals-table').innerHTML = state.meals.length ? state.meals.map(m => `<tr><td>${prettyDate(m.date)}</td><td>${m.mealType}</td><td><b>${escapeHtml(m.menu)}</b><br><span class="muted">${m.ingredients.length} ingredient${m.ingredients.length === 1 ? '' : 's'}</span></td><td>${m.expectedStudents}</td><td><button class="table-action" onclick="deleteMeal('${m._id}')">Delete</button></td></tr>`).join('') : empty('No meal plans yet. Create your first plan.', 5); }
function renderInventory() { $('#inventory-count').textContent = `${state.inventory.length} items`; $('#inventory-table').innerHTML = state.inventory.length ? state.inventory.map(i => { const low = i.currentQuantity < i.minimumStock; return `<tr><td><b>${escapeHtml(i.ingredientName)}</b></td><td>${i.currentQuantity} ${i.unit}</td><td>${i.minimumStock} ${i.unit}</td><td>${escapeHtml(i.supplierName)}</td><td><span class="badge ${low ? 'low' : 'ok'}">${low ? 'LOW STOCK' : 'SUFFICIENT'}</span></td><td><button class="table-action edit" onclick="editInventory('${i._id}')">Edit</button><button class="table-action" onclick="deleteInventory('${i._id}')">Delete</button></td></tr>`; }).join('') : empty('No inventory items yet.', 6); }
function renderWaste() { $('#waste-count').textContent = `${state.waste.length} records`; $('#waste-table').innerHTML = state.waste.length ? state.waste.map(w => `<tr><td>${prettyDate(w.date)}</td><td>${escapeHtml(w.meal)}</td><td>${escapeHtml(w.ingredientName || 'Not recorded')}</td><td>${w.preparedQuantity}</td><td>${w.consumedQuantity}</td><td>${w.wasteQuantity}</td><td><span class="badge ${w.wastePercentage > 10 ? 'low' : 'ok'}">${w.wastePercentage}%</span></td><td><button class="table-action" onclick="deleteWaste('${w._id}')">Delete</button></td></tr>`).join('') : empty('No waste records yet.', 8); }
function renderProcurement() { $('#procurement-table').innerHTML = state.procurement.length ? state.procurement.map(p => `<tr><td><b>${escapeHtml(p.ingredient)}</b></td><td>${p.requiredQuantity} ${p.unit}</td><td>${p.availableQuantity} ${p.unit}</td><td>${p.purchaseRequired} ${p.unit}</td><td><span class="badge ${p.status === 'PURCHASE REQUIRED' ? 'purchase' : 'ok'}">${p.status}</span></td></tr>`).join('') : empty('Add ingredients to a meal plan to see procurement requirements.', 5); }
function renderDashboard() { if (!state.dashboard) return; const { metrics, todayMeals, lowStockItems, recentWaste } = state.dashboard; $('#stat-students').textContent = metrics.expectedStudents; $('#stat-meals').textContent = metrics.plannedMeals; $('#stat-inventory').textContent = metrics.inventoryItems; $('#stat-low').textContent = metrics.lowStockItems; $('#stat-procurement').textContent = metrics.purchaseItems; $('#stat-waste').textContent = metrics.wasteQuantity; $('#stat-waste').nextElementSibling.textContent = `${metrics.wasteRecordCount} record${metrics.wasteRecordCount === 1 ? '' : 's'} today`; $('#today-meals').innerHTML = todayMeals.length ? `<div class="mini-list">${todayMeals.map(m => `<div class="mini-item"><div><b>${escapeHtml(m.menu)}</b><br><span>${m.mealType}</span></div><b>${m.expectedStudents} students</b></div>`).join('')}</div>` : '<p class="empty">No meals planned for today.</p>'; $('#low-stock').innerHTML = lowStockItems.length ? `<div class="mini-list">${lowStockItems.map(i => `<div class="mini-item"><div><b>${escapeHtml(i.ingredientName)}</b><br><span>Minimum: ${i.minimumStock} ${i.unit}</span></div><span class="badge low">${i.currentQuantity} ${i.unit}</span></div>`).join('')}</div>` : '<p class="empty">All inventory levels look healthy.</p>'; $('#recent-waste').innerHTML = recentWaste.length ? `<div class="mini-list">${recentWaste.map(w => `<div class="mini-item"><div><b>${escapeHtml(w.meal)}</b><br><span>${escapeHtml(w.ingredientName || 'Item not recorded')} · ${prettyDate(w.date)}</span></div><b>${w.wasteQuantity} portions · ${w.wastePercentage}%</b></div>`).join('')}</div>` : '<p class="empty">No waste records yet.</p>'; }
window.deleteMeal = async id => { if (!confirm('Delete this meal plan?')) return; try { await api(`/meals/${id}`, { method: 'DELETE' }); await refresh(); await loadProcurement(); toast('Meal plan deleted.'); } catch (e) { toast(e.message, true); } };
window.deleteInventory = async id => { if (!confirm('Delete this inventory item?')) return; try { await api(`/inventory/${id}`, { method: 'DELETE' }); await refresh(); await loadProcurement(); toast('Inventory item deleted.'); } catch (e) { toast(e.message, true); } };
window.deleteWaste = async id => { if (!confirm('Delete this waste record?')) return; try { await api(`/waste/${id}`, { method: 'DELETE' }); await refresh(); toast('Waste record deleted.'); } catch (e) { toast(e.message, true); } };
window.editInventory = id => { const item = state.inventory.find(i => i._id === id); const form = $('#inventory-form'); Object.entries(item).forEach(([key, value]) => { if (form.elements[key]) form.elements[key].value = value; }); $('#inventory-form-title').textContent = 'Edit inventory item'; $('#cancel-edit').classList.remove('hidden'); showPage('inventory'); window.scrollTo({ top: 0, behavior: 'smooth' }); };

document.addEventListener('DOMContentLoaded', () => { $('#today-label').textContent = new Date().toLocaleDateString('en-IN', { weekday: 'short', day: '2-digit', month: 'short' }); $$('input[type="date"]').forEach(input => input.value = dateValue()); addIngredient(); $$('.nav-link').forEach(button => button.onclick = () => showPage(button.dataset.page)); $$('[data-go]').forEach(button => button.onclick = () => showPage(button.dataset.go)); $('#add-ingredient').onclick = () => addIngredient(); $('#meal-form').onsubmit = async event => { event.preventDefault(); const form = event.currentTarget; const ingredients = [...$$('.ingredient-row')].map(r => ({ name: r.querySelector('.ingredient-name').value.trim(), quantityPerStudent: Number(r.querySelector('.ingredient-quantity').value), unit: r.querySelector('.ingredient-unit').value })).filter(i => i.name); try { await api('/meals', { method: 'POST', body: JSON.stringify({ ...Object.fromEntries(new FormData(form)), expectedStudents: Number(form.expectedStudents.value), ingredients }) }); form.reset(); form.date.value = dateValue(); $('#ingredient-list').innerHTML = ''; addIngredient(); await refresh(); await loadProcurement(); toast('Meal plan saved.'); } catch (e) { toast(e.message, true); } }; $('#inventory-form').onsubmit = async event => { event.preventDefault(); const form = event.currentTarget, values = Object.fromEntries(new FormData(form)); values.currentQuantity = Number(values.currentQuantity); values.minimumStock = Number(values.minimumStock); const url = values.id ? `/inventory/${values.id}` : '/inventory'; try { await api(url, { method: values.id ? 'PUT' : 'POST', body: JSON.stringify(values) }); form.reset(); $('#inventory-form-title').textContent = 'Add inventory item'; $('#cancel-edit').classList.add('hidden'); await refresh(); await loadProcurement(); toast('Inventory saved.'); } catch (e) { toast(e.message, true); } }; $('#cancel-edit').onclick = () => { $('#inventory-form').reset(); $('#inventory-form-title').textContent = 'Add inventory item'; $('#cancel-edit').classList.add('hidden'); }; const preview = () => { const f = $('#waste-form'); const p = Number(f.preparedQuantity.value), w = Number(f.wasteQuantity.value); $('#waste-preview').textContent = p > 0 ? `${((w / p) * 100).toFixed(2)}%` : '0%'; }; $('#waste-form').oninput = preview; $('#waste-form').onsubmit = async event => { event.preventDefault(); const form = event.currentTarget, values = Object.fromEntries(new FormData(form)); ['preparedQuantity', 'consumedQuantity', 'wasteQuantity'].forEach(k => values[k] = Number(values[k])); try { await api('/waste', { method: 'POST', body: JSON.stringify(values) }); form.reset(); form.date.value = dateValue(); preview(); await refresh(); toast('Waste record saved.'); } catch (e) { toast(e.message, true); } }; $('#refresh-procurement').onclick = async () => { await loadProcurement(); toast('Procurement calculation refreshed.'); }; initializeSession(); });

document.addEventListener('DOMContentLoaded', () => {
  $$('[data-auth-view]').forEach(button => button.onclick = () => { $('#login-form').classList.toggle('hidden', button.dataset.authView !== 'login'); $('#register-form').classList.toggle('hidden', button.dataset.authView !== 'register'); setAuthMessage(); });
  $('#login-form').onsubmit = async event => { event.preventDefault(); try { saveSession(await api('/auth/login', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) })); } catch (error) { setAuthMessage(error.message); } };
  $('#register-form').onsubmit = async event => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); if (values.password.length < 8) return setAuthMessage('Password must contain at least 8 characters.'); try { saveSession(await api('/auth/register', { method: 'POST', body: JSON.stringify(values) })); } catch (error) { setAuthMessage(error.message); } };
  $('#logout-button').onclick = logout;
});
