import { ArrowDownRight, ArrowUpRight, BarChart3, CalendarDays, Download, Lightbulb, TrendingUp, Users } from "lucide-react";
import { CategoryChart, GroupContributionChart, SpendingChart } from "@/components/dashboard/charts";
import { PageFrame, PageHeader } from "@/components/dashboard/page-header";
import { Button } from "@/components/ui/button";

const metrics = [["Total group spend", "₹18,420", "12.5%", true], ["Average expense", "₹768", "4.8%", false], ["Settlement rate", "92%", "6.2%", true], ["Active contributors", "27", "3 new", true]];
export default function AnalyticsPage() { return <PageFrame><PageHeader title="Analytics" description="A focused view of your shared financial habits." icon={BarChart3} action={<div className="flex gap-2"><Button variant="secondary"><CalendarDays className="size-4" /> This month</Button><Button variant="secondary" className="hidden sm:inline-flex"><Download className="size-4" /> Export</Button></div>} />
  <section className="grid gap-4 sm:grid-cols-2 2xl:grid-cols-4">{metrics.map(([label, value, change, isPositive]) => <article className="surface p-5" key={label as string}><p className="text-sm text-muted-foreground">{label as string}</p><div className="mt-2 flex items-end justify-between gap-3"><p className="text-2xl font-semibold tracking-tight">{value as string}</p><span className={`flex items-center gap-1 text-xs font-medium ${isPositive ? "text-emerald-600" : "text-rose-500"}`}>{isPositive ? <ArrowUpRight className="size-3.5" /> : <ArrowDownRight className="size-3.5" />}{change as string}</span></div><p className="mt-3 text-xs text-muted-foreground">Compared with last month</p></article>)}</section>
  <section className="mt-6 grid gap-6 2xl:grid-cols-[minmax(0,1.65fr)_minmax(320px,.85fr)]"><article className="surface overflow-hidden"><div className="flex flex-wrap items-start justify-between gap-3 border-b p-5"><div><h2 className="font-semibold">Spending trend</h2><p className="mt-1 text-sm text-muted-foreground">How shared spending has changed over time.</p></div><span className="rounded-lg bg-emerald-50 px-2.5 py-1.5 text-xs font-semibold text-emerald-600 dark:bg-emerald-950">+15.4% growth</span></div><div className="p-4 sm:p-5"><SpendingChart /></div></article><article className="surface p-5"><h2 className="font-semibold">Expense categories</h2><p className="mt-1 text-sm text-muted-foreground">Where this month’s money went.</p><CategoryChart /><div className="grid grid-cols-2 gap-y-3 border-t pt-4 text-xs text-muted-foreground">{[["Food & dining", "42%", "bg-blue-600"], ["Travel", "24%", "bg-emerald-500"], ["Projects", "18%", "bg-violet-500"], ["Other", "16%", "bg-amber-500"]].map(([name, value, colour]) => <div className="flex items-center gap-2" key={name}><span className={`size-2 rounded-full ${colour}`} /><span>{name}</span><span className="ml-auto mr-4 font-medium text-foreground">{value}</span></div>)}</div></article></section>
  <section className="mt-6 grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><article className="surface p-5"><div className="flex items-start justify-between"><div><h2 className="font-semibold">Group contribution</h2><p className="mt-1 text-sm text-muted-foreground">Which groups are driving shared spending.</p></div><Users className="size-5 text-primary" /></div><div className="mt-4"><GroupContributionChart /></div></article><article className="surface p-5"><div className="flex items-start gap-3"><div className="grid size-10 place-items-center rounded-xl bg-amber-50 text-amber-600 dark:bg-amber-950"><Lightbulb className="size-5" /></div><div><p className="text-sm font-semibold text-amber-700 dark:text-amber-400">Spending insight</p><h2 className="mt-2 font-semibold">Food spending is your largest category</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">It is 18% higher than last month, mostly from Hostel Block A’s shared groceries.</p></div></div><button className="mt-5 inline-flex items-center gap-2 text-sm font-medium text-primary">See category details <TrendingUp className="size-4" /></button></article></section>
  <section className="surface mt-6 p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-semibold">Settlement health</h2><p className="mt-1 text-sm text-muted-foreground">How efficiently your groups are keeping balances clear.</p></div><span className="rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-semibold text-emerald-600 dark:bg-emerald-950">Healthy</span></div><div className="mt-6 grid gap-4 sm:grid-cols-3">{[["92%", "Settled on time", "Most payments are cleared before a reminder."], ["₹1,825", "Pending amount", "Two settlements are waiting this week."], ["3.2 days", "Average settle time", "0.8 days faster than last month."]].map(([value, label, copy]) => <div className="rounded-xl border bg-muted/30 p-4" key={label}><p className="text-2xl font-semibold">{value}</p><p className="mt-1 text-sm font-medium">{label}</p><p className="mt-2 text-xs leading-5 text-muted-foreground">{copy}</p></div>)}</div></section>
  </PageFrame>; }
