"use client";
import Link from "next/link";
import { CalendarDays, ChevronDown, Download, Filter, Plus, ReceiptText, Search, SlidersHorizontal } from "lucide-react";
import { useMemo, useState } from "react";
import { PageFrame, PageHeader } from "@/components/dashboard/page-header";
import { ExpenseRow } from "@/components/dashboard/expense-row";
import { Button } from "@/components/ui/button";
import { expenses } from "@/constants/mock-data";
import { formatCurrency } from "@/lib/utils";

export default function ExpensesPage() {
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("all");
  const visibleExpenses = useMemo(() => expenses.concat(expenses).filter((expense) => (expense.title + expense.group).toLowerCase().includes(query.toLowerCase()) && (status === "all" || expense.status === status)), [query, status]);
  return <PageFrame><PageHeader title="Expenses" description="Track every shared expense in one calm place." icon={ReceiptText} action={<Link href="/expenses/add"><Button><Plus className="size-4" /> Add expense</Button></Link>} />
    <section className="grid gap-4 sm:grid-cols-3"><Summary label="This month" value="₹7,640" note="24 expenses added" /><Summary label="You paid" value="₹4,520" note="Across 3 groups" /><Summary label="You are owed" value="₹1,240" note="From 4 members" accent="text-emerald-600" /></section>
    <section className="surface mt-6 overflow-hidden"><div className="flex flex-col gap-4 border-b p-4 lg:flex-row lg:items-center lg:justify-between"><label className="flex h-11 w-full items-center gap-2 rounded-xl bg-muted/60 px-3 lg:max-w-md"><Search className="size-4 text-muted-foreground" /><input className="w-full bg-transparent text-sm placeholder:text-muted-foreground" onChange={(event) => setQuery(event.target.value)} placeholder="Search by expense or group" value={query} /></label><div className="flex flex-wrap gap-2"><button className="inline-flex h-10 items-center gap-2 rounded-xl border bg-card px-3 text-sm font-medium hover:bg-muted"><CalendarDays className="size-4" /> This month <ChevronDown className="size-3.5" /></button><button className="inline-flex h-10 items-center gap-2 rounded-xl border bg-card px-3 text-sm font-medium hover:bg-muted"><SlidersHorizontal className="size-4" /> Sort</button><button className="inline-flex h-10 items-center gap-2 rounded-xl border bg-card px-3 text-sm font-medium hover:bg-muted"><Download className="size-4" /> Export</button></div></div><div className="flex gap-1 overflow-x-auto border-b p-2">{[["all", "All expenses"], ["pending", "You lent"], ["you-owe", "You owe"], ["settled", "Settled"]].map(([value, label]) => <button className={`whitespace-nowrap rounded-lg px-3 py-2 text-sm font-medium transition-colors ${status === value ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:bg-muted hover:text-foreground"}`} key={value} onClick={() => setStatus(value)}>{label}</button>)}</div><div className="hidden grid-cols-[minmax(0,1fr)_150px_150px_120px] gap-4 border-b px-6 py-3 text-xs font-semibold uppercase tracking-wide text-muted-foreground lg:grid"><span>Expense</span><span>Paid by</span><span>Amount</span><span>Status</span></div><div className="p-3">{visibleExpenses.map((expense, index) => <Link href={`/expenses/${expense.id.toLowerCase()}`} key={`${expense.id}-${index}`}><ExpenseRow expense={expense} /></Link>)}{visibleExpenses.length === 0 && <div className="grid min-h-56 place-items-center text-center"><div><Filter className="mx-auto size-7 text-muted-foreground" /><p className="mt-3 font-medium">No expenses found</p><p className="mt-1 text-sm text-muted-foreground">Try adjusting your search or filters.</p></div></div>}</div></section></PageFrame>;
}
function Summary({ label, value, note, accent = "text-foreground" }: { label: string; value: string; note: string; accent?: string }) { return <article className="surface p-5"><p className="text-sm text-muted-foreground">{label}</p><p className={`mt-2 text-2xl font-semibold tracking-tight ${accent}`}>{value}</p><p className="mt-2 text-xs text-muted-foreground">{note}</p></article>; }
