"use client";
import { memo } from "react";
import { Area, AreaChart, Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { categoryData, spendingData } from "@/constants/mock-data";

const tooltipStyle = { borderRadius: 12, border: "none", boxShadow: "0 8px 24px rgba(0,0,0,.12)" };
export const SpendingChart = memo(function SpendingChart() { return <ResponsiveContainer width="100%" height={260}><AreaChart data={spendingData} margin={{ left: -20, right: 8 }}><defs><linearGradient id="spending" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#2563eb" stopOpacity={0.3} /><stop offset="100%" stopColor="#2563eb" stopOpacity={0} /></linearGradient></defs><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: "#94a3b8", fontSize: 12 }} /><YAxis axisLine={false} tickLine={false} tick={{ fill: "#94a3b8", fontSize: 12 }} tickFormatter={(value) => `₹${value / 1000}k`} /><Tooltip formatter={(value) => [`₹${value}`, "Spending"]} contentStyle={tooltipStyle} /><Area type="monotone" dataKey="amount" stroke="#2563eb" strokeWidth={3} fill="url(#spending)" /></AreaChart></ResponsiveContainer>; });
export const CategoryChart = memo(function CategoryChart() { return <div className="relative h-[260px]"><ResponsiveContainer><PieChart><Pie data={categoryData} dataKey="value" innerRadius={66} outerRadius={92} paddingAngle={5} stroke="none">{categoryData.map((entry) => <Cell key={entry.name} fill={entry.color} />)}</Pie><Tooltip formatter={(value) => [`${value}%`, "Share"]} contentStyle={tooltipStyle} /></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 grid place-items-center text-center"><div><p className="text-2xl font-semibold">₹7.6k</p><p className="text-xs text-muted-foreground">this month</p></div></div></div>; });
const groupContributionData = [{ group: "Hostel", amount: 8640 }, { group: "CodeFest", amount: 6120 }, { group: "Weekend", amount: 3920 }, { group: "Robotics", amount: 2840 }];
export const GroupContributionChart = memo(function GroupContributionChart() { return <ResponsiveContainer width="100%" height={250}><BarChart data={groupContributionData} layout="vertical" margin={{ left: 10, right: 18 }}><XAxis type="number" axisLine={false} tickLine={false} tick={{ fill: "#94a3b8", fontSize: 12 }} tickFormatter={(value) => `₹${value / 1000}k`} /><YAxis dataKey="group" type="category" axisLine={false} tickLine={false} tick={{ fill: "#64748b", fontSize: 12 }} width={68} /><Tooltip formatter={(value) => [`₹${value}`, "Total spend"]} contentStyle={tooltipStyle} /><Bar dataKey="amount" fill="#10b981" radius={[0, 7, 7, 0]} barSize={18} /></BarChart></ResponsiveContainer>; });
