import Link from "next/link";
import { ArrowRight, ArrowUpRight, BellRing, CalendarDays, CheckCircle2, ChevronRight, CreditCard, Plus, ReceiptText, Send, Users, Wallet } from "lucide-react";
import { Button } from "@/components/ui/button";
import { CategoryChart, SpendingChart } from "@/components/dashboard/charts";
import { ExpenseRow } from "@/components/dashboard/expense-row";
import { StatCard } from "@/components/dashboard/stat-card";
import { expenses, groups } from "@/constants/mock-data";
import { formatCurrency } from "@/lib/utils";

const legend = [["Food", "bg-blue-600"], ["Travel", "bg-emerald-500"], ["Projects", "bg-violet-500"], ["Other", "bg-amber-500"]];

export default function DashboardPage() {
  return <div className="mx-auto max-w-[1440px] p-4 md:p-6 xl:p-8">
    <header className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="flex items-center gap-2 text-sm font-medium text-emerald-600"><span className="size-2 rounded-full bg-emerald-500" /> Tuesday, April 22</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Good morning, Arjun</h1><p className="mt-1.5 text-sm text-muted-foreground">Here is the financial pulse across your campus groups.</p></div><div className="flex gap-2"><Link href="/groups/create"><Button variant="secondary" className="hidden sm:inline-flex"><Users className="size-4" /> New group</Button></Link><Link href="/expenses/add"><Button><Plus className="size-4" /> Add expense</Button></Link></div></header>

    <section className="grid gap-4 sm:grid-cols-2 2xl:grid-cols-4"><StatCard label="Total expenses" value="₹18,420" change="12.5%" icon={Wallet} /><StatCard label="Pending payments" value="₹1,825" change="8.2%" icon={CreditCard} positive={false} /><StatCard label="Active groups" value="08" change="2 new" icon={Users} /><StatCard label="Monthly spending" value="₹7,640" change="15.4%" icon={ReceiptText} /></section>

    <section className="mt-6 grid gap-6 2xl:grid-cols-[minmax(0,1.65fr)_minmax(320px,.85fr)]"><div className="space-y-6"><article className="surface overflow-hidden"><div className="flex flex-wrap items-start justify-between gap-3 border-b p-5"><div><h2 className="font-semibold">Spending overview</h2><p className="mt-1 text-sm text-muted-foreground">Your shared spending over the last six months.</p></div><button className="rounded-lg border bg-card px-3 py-1.5 text-xs font-medium transition-colors hover:bg-muted">Last 6 months</button></div><div className="p-4 sm:p-5"><SpendingChart /></div></article>
      <article className="surface"><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-semibold">Recent activity</h2><p className="mt-1 text-sm text-muted-foreground">The latest across every group.</p></div><Link href="/expenses" className="hidden text-sm font-medium text-primary sm:block">View all</Link></div><div className="p-3">{expenses.map((expense) => <ExpenseRow key={expense.id} expense={expense} />)}</div><Link href="/expenses" className="flex items-center justify-center gap-1 border-t py-3 text-sm font-medium text-primary sm:hidden">View all expenses <ArrowRight className="size-4" /></Link></article></div>

      <aside className="space-y-6"><article className="surface p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">By category</h2><p className="mt-1 text-sm text-muted-foreground">This month’s split.</p></div><button className="rounded-lg p-1.5 text-muted-foreground hover:bg-muted"><ChevronRight className="size-4" /></button></div><CategoryChart /><div className="grid grid-cols-2 gap-x-4 gap-y-3 border-t pt-4">{legend.map(([name, colour]) => <div className="flex items-center gap-2 text-xs text-muted-foreground" key={name}><span className={`size-2 rounded-full ${colour}`} />{name}</div>)}</div></article>
        <article className="overflow-hidden rounded-2xl bg-gradient-to-br from-blue-700 to-blue-950 p-5 text-white shadow-lg shadow-blue-950/20"><div className="flex items-start justify-between"><div><p className="text-sm text-blue-100">Settle up this week</p><h2 className="mt-2 text-3xl font-semibold">₹1,825</h2></div><span className="grid size-10 place-items-center rounded-xl bg-white/10"><Send className="size-5" /></span></div><p className="mt-4 text-sm leading-6 text-blue-100">Two payments are ready to settle. Keep your group balances clear.</p><Link href="/settlements"><Button className="mt-5 w-full bg-white text-blue-900 shadow-none hover:bg-blue-50">Review settlements <ArrowRight className="size-4" /></Button></Link></article>
        <article className="surface p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Your groups</h2><p className="mt-1 text-sm text-muted-foreground">Active this week</p></div><Link href="/groups" className="text-sm font-medium text-primary">Manage</Link></div><div className="mt-5 space-y-4">{groups.map((group) => <div key={group.name} className="flex items-center gap-3"><div className={`grid size-10 place-items-center rounded-xl bg-gradient-to-br text-xs font-bold text-white ${group.color}`}>{group.initials}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{group.name}</p><p className="text-xs text-muted-foreground">{group.members} members</p></div><p className={group.balance > 0 ? "text-sm font-semibold text-emerald-600" : group.balance < 0 ? "text-sm font-semibold text-rose-500" : "text-xs font-medium text-muted-foreground"}>{group.balance === 0 ? "All clear" : formatCurrency(Math.abs(group.balance))}</p></div>)}</div><Link href="/groups/create"><Button variant="secondary" className="mt-5 w-full">Create another group <ArrowUpRight className="size-4" /></Button></Link></article></aside>
    </section>

    <section className="mt-6 grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><article className="surface p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Upcoming</h2><p className="mt-1 text-sm text-muted-foreground">The next moments that need your attention.</p></div><CalendarDays className="size-5 text-primary" /></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{[["Today", "Rohan’s settlement is due", "₹465 to CodeFest ’26"], ["Friday", "Budget review", "CodeFest ’26 · 68% used"]].map(([date, title, detail]) => <div className="rounded-xl border bg-muted/30 p-4" key={title}><p className="text-xs font-semibold text-emerald-600">{date}</p><p className="mt-2 text-sm font-medium">{title}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div>)}</div></article><article className="surface p-5"><div className="flex gap-3"><div className="grid size-10 place-items-center rounded-xl bg-emerald-50 text-emerald-600 dark:bg-emerald-950"><CheckCircle2 className="size-5" /></div><div><h2 className="font-semibold">Your groups look healthy</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">12 settlements completed this month. Nice work keeping things clear.</p></div></div><button className="mt-4 flex items-center gap-2 text-sm font-medium text-primary"><BellRing className="size-4" /> Manage reminders</button></article></section>
  </div>;
}
