import Link from "next/link";
import { Check, CircleDollarSign, ShieldCheck, Sparkles, UsersRound } from "lucide-react";

export function AuthBrand() {
  return <Link href="/" className="flex items-center gap-2.5 text-lg font-bold tracking-tight"><span className="grid size-9 place-items-center rounded-xl bg-gradient-to-br from-blue-600 to-emerald-500 text-sm text-white shadow-lg shadow-blue-600/20">C</span>CampusSplit<span className="text-emerald-500">AI</span></Link>;
}

export function AuthShell({ children }: { children: React.ReactNode }) {
  return <main className="min-h-screen bg-background lg:grid lg:grid-cols-2" id="main-content"><section className="flex min-h-screen items-center justify-center p-5 sm:p-8">{children}</section><aside className="relative hidden overflow-hidden bg-slate-950 p-10 text-white lg:block"><div className="absolute -right-32 -top-24 size-96 rounded-full bg-blue-500/25 blur-3xl" /><div className="absolute -bottom-24 -left-24 size-80 rounded-full bg-emerald-500/20 blur-3xl" /><div className="relative mx-auto flex h-full max-w-lg flex-col"><AuthBrand /><div className="my-auto"><p className="flex items-center gap-2 text-sm font-medium text-emerald-400"><Sparkles className="size-4" /> Made for campus collaboration</p><h1 className="mt-5 text-4xl font-semibold leading-tight tracking-tight">The clear way to manage shared campus money.</h1><p className="mt-5 max-w-md text-base leading-7 text-slate-300">From hostel groceries to your next big event, CampusSplit keeps every shared expense simple, visible, and fair.</p><div className="mt-10 grid gap-3 sm:grid-cols-3">{[[CircleDollarSign, "Clear balances"], [UsersRound, "Better groups"], [ShieldCheck, "Private by default"]].map(([Icon, text]) => { const FeatureIcon = Icon as typeof CircleDollarSign; return <div className="rounded-xl border border-white/10 bg-white/5 p-3" key={text as string}><FeatureIcon aria-hidden="true" className="size-4 text-emerald-400" /><p className="mt-3 text-xs font-medium text-slate-200">{text as string}</p></div>; })}</div></div><p className="flex items-center gap-2 text-xs text-slate-400"><Check aria-hidden="true" className="size-3.5 text-emerald-400" /> Built for students, teams, and campus communities.</p></div></aside></main>;
}
