"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { BarChart3, Bell, CreditCard, LayoutDashboard, ReceiptText, ScanLine, Settings, Users, WalletCards, X } from "lucide-react";
import { cn } from "@/lib/utils";
import { useUIStore } from "@/store/ui-store";
const nav = [{ label: "Dashboard", href: "/dashboard", icon: LayoutDashboard }, { label: "Groups", href: "/groups", icon: Users }, { label: "Expenses", href: "/expenses", icon: ReceiptText }, { label: "Settlements", href: "/settlements", icon: CreditCard }, { label: "Analytics", href: "/analytics", icon: BarChart3 }];
const tools = [{ label: "Event budget", href: "/event-budget", icon: WalletCards }, { label: "Receipt scanner", href: "/receipt-scanner", icon: ScanLine }, { label: "Notifications", href: "/notifications", icon: Bell }];
export function Sidebar() { const pathname = usePathname(); const sidebarOpen = useUIStore((state) => state.sidebarOpen); const setSidebarOpen = useUIStore((state) => state.setSidebarOpen); const item = (n: typeof nav[number]) => { const active = pathname === n.href || n.href !== "/dashboard" && pathname.startsWith(`${n.href}/`); return <Link aria-current={active ? "page" : undefined} key={n.href} href={n.href} className={cn("flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary", active ? "bg-blue-600 text-white shadow-lg shadow-blue-600/20" : "text-muted-foreground hover:bg-muted hover:text-foreground")}><n.icon aria-hidden="true" className="size-[18px]" />{n.label}</Link>; };
 return <aside aria-label="Main navigation" className={cn("fixed inset-y-0 left-0 z-40 flex w-[260px] flex-col border-r bg-card p-4 transition-transform duration-300 motion-reduce:transition-none lg:static", !sidebarOpen && "-translate-x-full lg:w-[76px] lg:translate-x-0", sidebarOpen && "translate-x-0")}><div className="mb-9 flex items-center justify-between px-2"><Link href="/" className="flex items-center gap-2.5 overflow-hidden"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-gradient-to-br from-blue-600 to-emerald-500 font-bold text-white">C</span><span className={cn("whitespace-nowrap text-lg font-bold", !sidebarOpen && "lg:hidden")}>CampusSplit<span className="text-emerald-500">AI</span></span></Link><button aria-label="Close navigation" className="rounded-lg p-1 hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary lg:hidden" onClick={() => setSidebarOpen(false)}><X aria-hidden="true" /></button></div><nav aria-label="Product navigation" className="space-y-1">{nav.map(item)}</nav><p className={cn("mb-2 mt-8 px-3 text-[11px] font-semibold uppercase tracking-wider text-muted-foreground", !sidebarOpen && "lg:hidden")}>Workspace</p><nav aria-label="Workspace navigation" className="space-y-1">{tools.map(item)}</nav><div className="mt-auto rounded-2xl bg-gradient-to-br from-blue-600 to-blue-800 p-4 text-white"><p className="text-sm font-semibold">Campus Pro</p><p className="mt-1 text-xs text-blue-100">Unlock unlimited groups.</p><button className="mt-3 text-xs font-semibold underline underline-offset-4 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white">Explore plans</button></div></aside>; }
